# Generated by Django 3.1.1 on 2020-09-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200920_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='github',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AddField(
            model_name='post',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
